### ISSUE TITLE
"Debug assertion failed" error on Windows

### ISSUE THREAD

**Issue by jotaro-sama** [owl-project/owl#107]
This issue happens on all the samples I've tried to run, but I will refer to `sample00-rayGenOnly` for simplicity.

I've successfully built the project on Windows following the instructions on the `README` (I am using CMake GUI and the Visual Studio 2019 generator), but when I run the `sample00-rayGenOnly` I get a `Microsoft Visual C++ Runtime Library` popup window with the following error:

```
Debug Assertion Failed!

Program:
[...]\sample00-rayGenOnly.exe
File: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\xtree
Line: 181

Expression: cannot dereference value-initialized map/set iterator
```

Funnily enough, the output image still gets generated, at least in this simple example, but this error is quite annoying and I'm not sure how it would play out in a more complex program using OWL.

**Comment by ingowald** [comment]
Thanks for pointing that out; i'll have a look. Seems this is happening upon shutdown of the OWL context, basically once your program is already done; still needs to get fixed, but at least shouldn't have any influence on anything you do while your program is still running. I'll have a look!

**Comment by ingowald** [comment]
This seems to have been an issue in owlContextDestroy, where it tried to automatically destroy/release all those objects that the user had created by not yet released. Based on some comments in that respective code that had pparently caused some issues before, but had never been properly fixed. New code is completely rewritten, and seems to now work file, while still removing all objets. Closed.
