### ISSUE TITLE
Using tags for release versions

### ISSUE THREAD

**Issue by finartist** [owl-project/owl#117]
I would like to suggest to use git tags for release versions. It is nice that there is a revision history in the Readme but it can't be easily tracked to specific commits unless I'm missing something.

**Comment by ingowald** [comment]
Fully agree; we've actually let versioning and releasing slip quite a bit in general (we were more actively doing that when lots of things were still changing; but now that most things have settled down we've gotten a bit ... lazy). 
So from now on, let's create branches for "release-x.y", then tags for patch-releases a la release-x.y.z

**Comment by finartist** [comment]
I think ideally it would be possible to add owl in a project via [CPM](https://github.com/cpm-cmake/CPM.cmake). However, it requires a [certain project structure](https://github.com/cpm-cmake/CPM.cmake/wiki/Preparing-projects-for-CPM.cmake) to do this effectively. Mainly using modern CMake and a certain release tag structure. I would say owl isn't too far from it already and the open pull request already touches the CMake anyway.

**Comment by ingowald** [comment]
<groan>
I just figured out just why there are no release tags at all: git doesn't push tags by default, so all the tags I always created were never pushed.
Of course that doesn't fit the problem, just wanted to explain that we didn't just _forget_ about tagging, I just didn't realize they never got pushed. Will change from now on.
