### ISSUE TITLE
Formatting and wording issues in the OWL variables wiki page

### ISSUE THREAD

**Issue by jotaro-sama** [owl-project/owl#142]
I was reading [the wiki page about OWL Variables](https://github.com/owl-project/owl/wiki/Intro-to-OWL-Variables) and I would've liked to submit some formatting/wording fixes but sadly GitHub does not have wiki PRs or any other official mechanism for that yet. 

The best I can do for now is to report them as an issue:

1. In the [Declaring a type that uses Variables](https://github.com/owl-project/owl/wiki/Intro-to-OWL-Variables#declaring-a-type-that-uses-variables) entry these lines would probably be more readable in a code block:
```
OWLGeomType triMeshGT = owlGeomTypeCreate(context,sizeof(TriMeshType), triMeshVars, -1);

Similarly, we could create a raygen program, or launch parameters, using, e.g.,

OWLParams launchParams = owlParamsCreate(context,sizeof(MyLaunchParams), myLaunchParamsVars, -1);
``` 

2. In the [Setting Variables on the Host](https://github.com/owl-project/owl/wiki/Intro-to-OWL-Variables#setting-variables-on-the-host) section, a tick probably misses before OWLRayGen in the markdown, and as a result the monospace and non-monospace text are inverted. 
3. Same section, minor spelling issues: "a object" is written many times instead of "an object", and "Tough"  is written instead of "Though". 
4. Same section, the following sentence is a bit unclear: "Tough setting variables works exactly the same for ray-gens, geometries, params, etc, always works exactly the same way, when a owl<Type>Set() will take effect depend on what type of object gets set". Maybe it could be corrected as "Though setting variables works exactly the same for ray-gens, geometries, params, etc... when a `owl<Type>Set()` will take effect depends on what type of object gets set".

Hope these suggestions help in making the OWL docs even better!

**Comment by ingowald** [comment]
I _think_ I've just given you write access to that. Github is a bit weird with permissions, and I'm never sure what I'm changing for whom, but if I read the docs correctly you should be able to edit wiki pages if you hvae push access, and I _think_ i just gave you that, too. I'd appreciate you still using PRs for code (just so I can track what gets changed when), but either way you shold now be able to edit the wiki pages. (fingers crossed)

**Comment by jotaro-sama** [comment]
Thank you for trusting me with write access! I was indeed able to edit the wiki as described here, and of course I will still submit all code edits as PRs. 

I think we can close this issue now.
