### ISSUE TITLE
Issues with owl on Ubuntu 21.10

### ISSUE THREAD

**Issue by finartist** [owl-project/owl#144]
I recently got a new PC which is currently running Ubuntu 21.10. With the new Ubuntu versions also came a new **CMake** Version (**3.18.4** from previous 3.16.3), a new **g++** version (**11.20** from previous 9.3.0) which forced the use of **cuda 11.5 Update 1** (and therefore a new driver version) because of an issue with the glibc 2.34 (https://forums.developer.nvidia.com/t/cuda-11-5-samples-throw-multiple-error-attribute-malloc-does-not-take-arguments/192750).

---

Now, when I try to use owl as subproject in my project I get the following error from CMake:

> CUDA_ARCHITECTURES is empty for target "owl"

which I managed to workaround by setting the CUDA_ARCHITECTURES prior to adding owl. When I try to compile owl on it's own, the message does not appear and CMake configures fine. CUDA_ARCHITECTURES seems to be new in cmake 3.18 (https://cmake.org/cmake/help/git-stage/prop_tgt/CUDA_ARCHITECTURES.html) which explains why this never happened before for me.

---

When I use Optix 7.4.0 instead of 7.3.0, I get a compile error:
```
error: ‘OPTIX_COMPILE_DEBUG_LEVEL_LINEINFO’ was not declared in this scope; did you mean ‘OPTIX_COMPILE_DEBUG_LEVEL_MINIMAL’?
  262 | duleCompileOptions.debugLevel        = OPTIX_COMPILE_DEBUG_LEVEL_LINEINFO;
      |                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                        OPTIX_COMPILE_DEBUG_LEVEL_MINIMAL

```
for DeviceContext.cpp:262:46 and DeviceContext.cpp:268:46.

This is just the new OptiX Version and does not happen with 7.3.0. Changing the lines to the suggested code lets it compile without issue (however, I don't know if the behavior is the same for MINIMAL and LINEINFO).

---

The one thing I could not find a workaround or fix for is a linker issue:

> nvlink fatal   : Could not open input file '/usr/lib/x86_64-linux-gnu/librt.a'

which happens at the stage of `Linking CUDA device code CMakeFiles/owl.dir/cmake_device_link.o`. I tried using cuda 11.4, I tried using g++10, I tried a different OptiX version and I tried owl 1.1.3 and owl 1.1.5. OptiX and its samples compile fine, just owl does not. Is this a cuda issue or an owl issue?

**Comment by ingowald** [comment]
Thx for reporting this, lisa; i can reproduce with optix 7.4 even on ubuntu 20.04. Just pushing a fix for this, should be out in a few minutes.
One caveat: that push will mark the issue as resolved even though I haven't strictly tested on 20.10, or with the cuda and gcc versions you mention - I _assume_ it'll fix it on those as well, but if it doesn't please re-open. give me 5 minutes.

**Comment by finartist** [comment]
For the CUDA_ARCHITECTURES error I had to set the right cmake policy, but that is working now.  
The compile error is fixed as well.

However, the nvlink error still persists.  Digging around in the CMakeLists, I found this to be the culprit (`owl/CMakeLists.txt` line 143 to 157):
```CMAKE
# bind OWL to CUDA (includes and library)
if(${CMAKE_VERSION} VERSION_GREATER_EQUAL 3.17)             # <-- this case breaks the linking
  # for new cmake version, we can rely on the working cuda detection
  # mechanism
  find_package(CUDAToolkit REQUIRED)
  target_link_libraries(owl PUBLIC CUDA::cuda_driver CUDA::cudart_static)
else()                                                      # <-- using the else branch links perfectly fine
  # for older version of cmake (where CUDAToolkit detection doesn't
  # properly work) we fall back to search paths for hardcoded library
  # names and header name; this isn't clean, but applies only for a
  # small set of deprecated cmake versions, so OK for now.
  target_link_libraries(owl PUBLIC cuda)
  find_path(cuda_h_dir NAMES cuda.h HINTS /usr/local/cuda/include)
  target_include_directories(owl PUBLIC ${cuda_h_dir})
endif()
```
When looking at cmake --build with the verbose option, it shows that the first case for CMake 3.18 adds `/usr/lib/x86_64-linux-gnu/librt.a` specifically next to `-lrt`, while the else branch only adds `-lrt`. Apparently, `/usr/lib/x86_64-linux-gnu/librt.a` is incompatible for some reason? This also shows when setting the LIBRARIES environment variable to `/usr/lib/x86_64-linux-gnu`, because it will then show
 ```
nvlink warning : Skipping incompatible '/usr/lib/x86_64-linux-gnu/libdl.a' when searching for -ldl
nvlink warning : Skipping incompatible '/usr/lib/x86_64-linux-gnu/librt.a' when searching for -lrt
nvlink warning : Skipping incompatible '/usr/lib/x86_64-linux-gnu/libpthread.a' when searching for -lpthread
nvlink fatal   : Could not open input file '/usr/lib/x86_64-linux-gnu/librt.a'
```

**Comment by finartist** [comment]
There is [news about the linking issue](https://forums.developer.nvidia.com/t/findcudatoolkit-cmake-finds-incompatible-version-of-librt/198223/7?u=livelyliz) in case someone stumbles across this and faces the same issue. Replacing librt.a with an empty librt.a is working.

I guess all points in this issue are now solved (or worked around).
