### ISSUE TITLE
Wrong position suggested for the sponza assets on Windows when building the whole project all at once

### ISSUE THREAD

**Issue by jotaro-sama** [owl-project/owl#148]
Running the `optix7course`  sample, I realized that it suggests to put the `models` directory in the same directory as the code from the sample. However, at least for the way I compile the code on Windows with CMake and the VS generator, building all of owl at once, that is not the correct position for the assets to be placed.

The executable is in ` owl/build/Debug` , and in the case of Windows it looks for the ` ../../models` folder, because it assumes that the build directory is placed in the `optix7course` folder, while every executable is put in the `owl/build/Debug` folder if you build all the project and samples with VS.

**Comment by ingowald** [comment]
Could you provide a PR that fixes that? Thx

**Comment by jotaro-sama** [comment]
Ok
