### ISSUE TITLE
Question: Is it possible using other C++ libraries with OWL?

### ISSUE THREAD

**Issue by bipul-mohanto** [owl-project/owl#161]
Hi! 
as a very beginner level question, is it possible using other C/C++ libraries (e.g., OpenGL, OpenVR, etc.) with OWL for sharing the buffers and context?

**Comment by ingowald** [comment]
Yes; for any owl buffer you created, you can always ask for the device-address using owlBufferGetAddress(buffer,deviceID), then you can do with this device address whatever you want to do (e.g., directly cudaMemcpy into that address).

Same the other way around - though it's often easiest to use data through owl buffers (and program variables that expect "OWL_BUFFER" types) you can also use parameters that take external addresses (OWL_PARAM_RAW_POINTER or something like that).
