### ISSUE TITLE
Unknown CMake command "embed_ptx"

### ISSUE THREAD

**Issue by asprasan** [owl-project/owl#165]
I have installed Optix 7.1 and OWL through cmake on a Ubuntu 20.04 machine with a Nvidia Geforce 980 and cuda 11.4

I wanted to test the library. So, I tried to build the sample files in `samples/cmdline` using cmake. 
I did the following in the `samples/cmdline` directory:
```sh
mkdir build
cd build
cmake ..
```
cmake gave me an error with `Unknown CMake command "embed_ptx"`
Am I trying to run the code properly? I am new to both OptiX as well as C++. So, any leads will be helpful

P.S. I also tried to compile the code `samples/cmdline/s00-rayGenOnly` with g++, which gave me the error:
```sh
hostCode.cpp:22:10: fatal error: owl/owl.h: No such file or directory
   22 | #include <owl/owl.h>
```

**Comment by ingowald** [comment]
You have to build the project from the root dir; the CMakeLists.txt there will set up all the environmen t- including commands like embed_ptx - and then automatically recursive into the subdirectories. 

If you ever want to use an external project to use OWL you can cmake-include() the owl directory as a subdirectory, then that will also define this command for your own application; but the samples assume that they're built as _part_ of owl.

**Comment by asprasan** [comment]
I was looking for the sample code executables inside the `samples/cmdline` directory.
I did not notice that were created in the `build` directory.

Thank you for your help.
