### ISSUE TITLE
How to return the triangle intersection coordinate instead of the colour

### ISSUE THREAD

**Issue by asprasan** [owl-project/owl#170]
I have a particular application where I am more interested in finding the 3D point of the first intersection between the primary ray and the object.
To solve this, I was thinking of encoding the coordinates into the fbPtr buffer variable, instead of encoding RGB color value (as is normally done in sample codes).
I am curious if there are more elegant ways to achieve this? Any pointers in this direction will be helpful.

If the material at the first intersection is reflective/refractive then I am interested in obtaining the second intersection as well.

**Comment by ForceConstant** [comment]
I have been using this in the closest hit program to get the 3d point of the intersection.

```
  const vec3f rayDir = optixGetWorldRayDirection();
  const vec3f ray_orig = optixGetWorldRayOrigin();
  const float ray_t = optixGetRayTmax();
  vec3f hit_point = ray_orig + ray_t * rayDir;
```

**Comment by asprasan** [comment]
Yes. It should be possible to get the coordinate. but how do we return this value back to the main program?
Currently, I am assigning this value to the frame-buffer. Instead of assigning the RGB value, I assign this 3D co-ordinate (after scaling appropriately to ensure that the information isn't lost due to quantization).
I am just curious if there are any better ways to do this.

**Comment by szellmann** [comment]
It is certainly possible to return output from the OWL raygen program w/o abusing the frame buffer variable you find in the samples (it's of course also fine to do so, if you're ok with it, not explicitly discouraged).

_One_ out of potentially many ways is to create an owl buffer using `owlDeviceBufferCreate()` and with the size that you need, add the handle to that in the launch params like this:

`{ "myBufferPtr",  OWL_BUFPTR, OWL_OFFSETOF(LaunchParams,myBufferPtr)},`,

in your raygen prog, fill the buffer on the device, and then, after the launch returned, obtain the buffer's content using `cudaMemcpy(...,cudaMemcpyDeviceToHost);`.

Pointers to OWL buffers can be obtained using `owlBufferGetPointer()`, which, in the case of the device buffer will give you a raw pointer on the device. OWL buffers potentially live on multiple GPUs simultaneously, so you have to pass the `deviceID` to that function. In the simplest case of a single GPU, the `deviceID` is just 0.

Hope that helps, lmk if things are unclear, I can maybe point you to an example.

**Comment by asprasan** [comment]
I followed your instructions to some extent. I created a buffer, launchparams and assigned the buffer to launch parameter variables as:
```cpp
  std::vector<vec3f> CoordsBufferdata;
  vec3f zero_vec(0);
  for(int i=0; i< fbSize.x*fbSize.y; i++)
  	CoordsBufferdata.push_back(zero_vec);
  OWLVarDecl launchParamVars[] = {
    {"CoordsBuffer", OWL_BUFPTR, OWL_OFFSETOF(MyLaunchParams, CoordsBuffer)},
    {/*sentinel to mark end of list*/}
  };
  OWLBuffer CoordsBuffer
    = owlDeviceBufferCreate(context, OWL_FLOAT3, CoordsBufferdata.size(), CoordsBufferdata.data());
  OWLParams lp = owlParamsCreate(context,sizeof(MyLaunchParams),launchParamVars,-1);
```

My launch param struct looks like:
```cpp
   struct MyLaunchParams {
      float3 *CoordsBuffer;
   };
```

After calling `owlLaunch2D` (where I populate the CoordsBuffer with necessary data), I obtain the buffer pointer as:
```cpp
const float *cb
    = (const float*)owlBufferGetPointer(CoordsBuffer,0);
```
I am not entirely sure if I am doing this correctly.
And I am not sure of the usage of `cudaMemcpy(...,cudaMemcpyDeviceToHost);` part.
If you could point out an example of its usage, I would be very thankful.

**Comment by szellmann** [comment]
Here's a mini example, tested on Ubuntu 20.04, which, afaiu, is basically  what you're trying to do: https://github.com/szellmann/owl-buffer-example

It's just filling the coordinate buffer with some random integers (the launchID, actually), but I suppose you can easily copy from that.

Seems you're located in Bonn, so greetings from Cologne btw. which is pretty near :)
