### ISSUE TITLE
CUDA_ARCHITECTURES is empty for target "owl"

### ISSUE THREAD

**Issue by jctemp** [owl-project/owl#173]
## Expected Behaviour
- adding owl as submodule to a project with `git submodule add <repo>`
- `cd owl && git checkout v1.1.6` to use the release accordingly
- **Note:** the master branch does not show this behaviour

## Current Behaviour
- adding owl to the project as submodule and adding directory via this line
```
set(owl_dir "${CMAKE_CURRENT_SOURCE_DIR}/external/owl")
add_subdirectory(${owl_dir} EXCLUDE_FROM_ALL)
```
- changing to the directory of owl submodule and `git checkout v1.1.6`
- configuring CMAKE cache following error occurs: `CMake Error in external/owl/owl/CMakeLists.txt: CUDA_ARCHITECTURES is empty for target "owl".`

![image](https://user-images.githubusercontent.com/58829168/164892383-f7fdf743-aa46-40cf-8b12-b1610fc87649.png)

## Environment
- Windows 11 64-bit
- Owl 1.1.6 release
- C++ 20 / Cuda 17 / C 17
- cmake 3.22.0

**Comment by finartist** [comment]
Hey there, this happened to me too but I was able to work around it by setting the cuda architecture before adding owl to the project. If you don't know your cuda architecture (like me) then you may try setting it automatically. Unfortunately I don't remember what I did but I think it was [this](https://stackoverflow.com/a/69353718)

```
    if(${CMAKE_VERSION} VERSION_LESS_EQUAL "3.13.4")
      cuda_select_nvcc_arch_flags(ARCH_FLAGS "Auto") # optional argument for arch to add
      message("ARCH_FLAGS = ${ARCH_FLAGS}")
      string(REPLACE "-gencode;" "--generate-code=" ARCH_FLAGS "${ARCH_FLAGS}")
      string(APPEND CMAKE_CUDA_FLAGS "${ARCH_FLAGS}")
    else()
      include(FindCUDA/select_compute_arch)
      CUDA_DETECT_INSTALLED_GPUS(INSTALLED_GPU_CCS_1)
      string(STRIP "${INSTALLED_GPU_CCS_1}" INSTALLED_GPU_CCS_2)
      string(REPLACE " " ";" INSTALLED_GPU_CCS_3 "${INSTALLED_GPU_CCS_2}")
      string(REPLACE "." "" CUDA_ARCH_LIST "${INSTALLED_GPU_CCS_3}")
      SET(CMAKE_CUDA_ARCHITECTURES ${CUDA_ARCH_LIST})
      set_property(GLOBAL PROPERTY CUDA_ARCHITECTURES "${CUDA_ARCH_LIST}")
    endif()
```
a friend had the problem in an owl unrelated project and solved it with

```
cmake_policy(SET CMP0104 NEW)
set(CMAKE_CUDA_ARCHITECTURES OFF)
```

**Comment by jctemp** [comment]
Thank you for the answer. This here worked :)
```
cmake_policy(SET CMP0104 NEW)
set(CMAKE_CUDA_ARCHITECTURES OFF)
```
