### ISSUE TITLE
Moved mesh group with owlInstanceGroupSetTransform, and need moved vertices in device code.

### ISSUE THREAD

**Issue by ForceConstant** [owl-project/owl#176]
As title says, I moved a mesh using owlInstanceGroupSetTransform(), and thought I could just do something like `optixTransformNormalFromObjectToWorldSpace(sbtData.vertex[index.x])` in device code, but doesn't seem to work correctly.  I do see the actual hit point moving but the vertices stay the same. It seems to work ok if I just change rotation of mesh, but not if I change position of mesh. What do I need to add?

**Comment by szellmann** [comment]
Are you sure you're using the correction function? For 3D points I would use `optixTransformPointFromObjectToWorldSpace`. `optixTransformNormalFromObjectToWorldSpace` will use the inverse transposed of the instance matrix to transform the _normal_ vector, but as you're referring to vertices in your code snippet, I wonder if that's what you want?

**Comment by szellmann** [comment]
For a little more context, see this [link](https://paroj.github.io/gltut/Illumination/Tut09%20Normal%20Transformation.html), which explains how normals are transformed. As you're saying that the vertices rotate but don't move, makes me relatively confident that that's the issue you're running into.

**Comment by ForceConstant** [comment]
@szellmann No you first comment was correct, I had mistakenly used the wrong transform function, and needed the points one.
Thanks.
