### ISSUE TITLE
Any ideas how I could use this library in Unity Engine?

### ISSUE THREAD

**Issue by ForceConstant** [owl-project/owl#186]
I have OWL/Optix running in a standalone application, and am seeing if I can port this to a Unity project. Ideally it would be in such a way that Unity would handle all the Meshes, etc. and then a call to owlLaunch2D would work as normal. Any idea of how this could be accomplished?

**Comment by ingowald** [comment]
This is probably more a question for the Unity folks. Having just had a brief glimpse unity seems to have a concept of user-provided "render pipelines" that _sound_ like what you're describing ... but I'm by no means a unity expert.
