### ISSUE TITLE
could you please give an example to show how to pass a transform matrix to traversable objects using owl? 

### ISSUE THREAD

**Issue by WangZilu0218** [owl-project/owl#189]

**Comment by WangZilu0218** [comment]
specially to show how to set static transform and motion transform,  thank you !

**Comment by ingowald** [comment]
You don't set the transform on an _object_, you'd set the transform of an _instance_ that instantiates this object. Ie, you'd first create the geometries and group for the object, build the groups's accel (that's the traversable), then create an instance of that object. For that instance, you can then set the transform via, for example, `owlnstanceGroupSetTransform`. Best see example  https://github.com/owl-project/owl/blob/master/samples/interactive/int11-rotatingBoxes/hostCode.cpp . Don't foget to rebuild/refit the top-level accel, though, else changing the transform won't have any effect.

For motion blut see the motion blur example.

**Comment by ingowald** [comment]
assuming that fixed it; closing this.
