### ISSUE TITLE
owlLaunch2D fails with dimensions (>= 263200, 4080)

### ISSUE THREAD

**Issue by KungFuJesus** [owl-project/owl#213]
I'm not sure if this is a limitation of my ptx or some goofy limitation in the Optix API itself but owl comes back on the ray launch with:

```
Optix call (optixLaunch(device->pipeline, lpDD.stream, (CUdeviceptr)lpDD.deviceMemory.get(), lpDD.deviceMemory.sizeInBytes, &lpDD.sbt, dims.x,dims.y,dims.z )) failed with code 7050 (line 200)
```

I haven't tried this with simpler raygen programs, but it seems odd that it immediately fails to launch.  I don't _think_ it's overflow (the launch parameters themselves are well under the handful of billion a signed int32 can handle), and there are assertions in owl to make sure the dimensions are > 0.  I might be able to work around this with a 3d launch but it's confounding and I can't see anything in Optix's documentation to suggestion this sort of limitation for 2d launches.  Compiling with debug does not produce any more meaningful diagnostics.  I checked carefully in my wrapping code for overflow, as far as I can tell there is none.  The raygen program does produce multiple rays per thread, but up to this point that's not been a problem.

**Comment by KungFuJesus** [comment]
Redistributing the launches such that more are in the second dimension does not seem to fix the issue, either.  I can try a third dimension, but I suspect that may also fail.

**Comment by KungFuJesus** [comment]
Switching to a 3d launch also fails.  Internally the ray gen kernel is doing 5 separate ray launches, which with these dimensions could put us around overflow criteria (5 * 263200 * 4080 = 5,369,280,000).  

Do you know if nvidia is doing an unroll in the PTX maybe in 32 bits and this is overflowing?  

Samples seem to be working:
```
[astylinski@crushinator build]$ ./sample10-launch3D 
#owl.sample(main): owl example './sample10-launch3D' starting up
#owl.sample(main): creating the scene ...
#owl.sample(main): created scene:
#owl.sample(main):  num lambertian spheres: 388
#owl.sample(main):  num dielectric spheres: 34
#owl.sample(main):  num metal spheres     : 66
#owl.sample(main): building geometries ...
#owl.sample(main): launching ...
#owl.sample(main): done with launch, calling CUDA kernel to convert from float3 to rgba8 ...
#owl.sample(main): written rendered frame buffer to file s10-launch3D.png
#owl.sample(main): destroying devicegroup ...
#owl.sample(main): seems all went OK; app is done, this should be the last output ...
```

The tiny_objloader based sample failed to compile due to some C++ related issue, but I suspect everything is mostly working.

**Comment by ingowald** [comment]
Re the launch sizes: it's probably not an overflow; it's more related to the fact that owl builds on optix, which in turn builds on cuda, and there's some limitations on how big launches in cuda can be. 3D launch or just changing the "shape" of the launch is probably not going to fix it, because the total number of threads launched in that will still be too big.
What I'd suggest is try to split it into multiple smaller launches of, say, 4kx4k. If you use launch parameters and async lauches this isn't going to cost any performance, either, because you can actually already launch the second 4kx4k block before the first one is finished, etc.

**Comment by KungFuJesus** [comment]
Why won't nvidia document the limitations of this API if that's the case?  Having a hard number here would be nice.

**Comment by KungFuJesus** [comment]
Splitting into disparate launches did fix it (though I sort of already suspected it might when I was searching for the upper bound of launch size).  

I likely can't divulge too much about it but at the high level it's a massive ambient occlusion test for radar primitives.

**Comment by KungFuJesus** [comment]
Closing, as this definitely isn't an Owl issue.  It'd be great if the upperbound could be found for these launch sizes but I suspect if it's like CUDA, it's going to have a high degree of variability based on shared memory usage, register usage, and compute architecture.
