### ISSUE TITLE
device synchronizatoin after launch param launch only sync's first device

### ISSUE THREAD

**Issue by ingowald** [owl-project/owl#35]

**Comment by n8vm** [comment]
Some details:

This multi-device synchronization is important when writing to host mapped or managed memory pointers in between calls to param launch. Calling cudaStreamSynchronize after launch might fix the issue, although another fix would be to loop through all devices, selecting and calling cudaDeviceSynchronize for each.

**Comment by ingowald** [comment]
fixed
