### ISSUE TITLE
Release with Debug builds in parent projects are disabled when including OWL

### ISSUE THREAD

**Issue by n8vm** [owl-project/owl#51]
When I add_subdirectory(owl), I was finding that my RelWithDebug and other build types disappeared. It took me a while to find, but it seems that the configure_build_type.cmake is sneakily deleting them. 

This was a pretty subtle issue I had a hard time fixing. I'd propose we remove that configure file, since OWL shouldn't be in control of parent project CMAKE_CONFIGURATION_TYPES or CMAKE_BUILD_TYPE.

**Comment by ingowald** [comment]
Huh. As long as it's included (only) via a add_subdirectory it should only affect the variables in that subdirectory, and not the parent one (unless somebody set those via PARENT_SCOPE, which I don't think we do)

**Comment by n8vm** [comment]
I thought so too, but it seems that's not the case for all variables. It seems for certain variables first declared globally,  submodules can override them. In my case, I use CMAKE_CONFIGURATION_TYPES  and CMAKE_BUILD_TYPE in my parent project before owl changes them.
