### ISSUE TITLE
feature request: support DDS file format

### ISSUE THREAD

**Issue by vinjn** [owl-project/owl#57]
It would be awesome if owl could support DDS file format :)

**Comment by ingowald** [comment]
Can you elaborate? OWL Isn't specifically a 'renderer" that reads different file formats - more of a library for _writing_ renders. 
Did you specifically mean that OWLTexture types should also support DXT compressed textures?

**Comment by vinjn** [comment]
>Did you specifically mean that OWLTexture types should also support DXT compressed textures?
Yes, exactly.
