### ISSUE TITLE
Link Error

### ISSUE THREAD

**Issue by ychding11** [owl-project/owl#91]
```
/usr/bin/ld: /usr/local/cuda-11.0/lib64/libcudart_static.a(libcudart_static.a.o): undefined reference to symbol 'pthread_rwlock_trywrlock@@GLIBC_2.2.5'
/lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line

```
gcc --version
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Thu_Jun_11_22:26:38_PDT_2020
Cuda compilation tools, release 11.0, V11.0.194
Build cuda_11.0_bu.TC445_37.28540450_0

**Comment by szellmann** [comment]
I (and believe some other people who also follow this project) have been investigating this issue a little bit. I believe it has to do with some changes to the FindCUDA.cmake module that comes with newer cmake versions. Are you using the cmake version that comes with Ubuntu 18.04 (via aptitude) or are you on a newer version? Could you check if rolling back to an older cmake version fixes that for you?

**Comment by ychding11** [comment]
@szellmann 
  
cmake --version
cmake version 3.20.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).

**Comment by szellmann** [comment]
I found that this combination worked for me:
```> cmake --version
cmake version 3.10.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
> cat /etc/issue
Ubuntu 18.04.3 LTS \n \l```

you could try to install cmake via `apt install cmake` and use that for the time being (if that's an option to you), only until we found a fix for the above. I couldn't look to deep into it so far but it could actually be a cmake and not an owl bug.

**Comment by ychding11** [comment]
cmake also complains 

```
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
```
It seems it requires to link against pthread explicitly.  Is there a simple walkaround ?

**Comment by ychding11** [comment]
> I found that this combination worked for me:
> 
> ```
> cmake version 3.10.2
> 
> CMake suite maintained and supported by Kitware (kitware.com/cmake).
> > cat /etc/issue
> Ubuntu 18.04.3 LTS \n \l
> ```
> 
> you could try to install cmake via `apt install cmake` and use that for the time being (if that's an option to you), only until we found a fix for the above. I couldn't look to deep into it so far but it could actually be a cmake and not an owl bug.

Ok, thanks. I would try it.

**Comment by szellmann** [comment]
I fixed that on devel, via https://github.com/owl-project/owl/pull/92

**Comment by ychding11** [comment]
Good Job! Thanks! @szellmann
